version: "3.8"

services:
    db:
      image: postgres:12
      restart: always
      environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cryptoats
      ports:
          - 15432:5432

    cryptoats:
      build: .
      volumes:
        - "$PWD:/app"
      depends_on:
        - db
      network_mode: host
